// Mocks generated by Mockito 5.4.6 from annotations
// in testable/test/core/services/api_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:dio/dio.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:testable/core/config/env.dart' as _i3;
import 'package:testable/core/network/dio/http_client.dart' as _i5;
import 'package:testable/core/utils/logger.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAppLogger_0 extends _i1.SmartFake implements _i2.AppLogger {
  _FakeAppLogger_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEnv_1 extends _i1.SmartFake implements _i3.Env {
  _FakeEnv_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDio_2 extends _i1.SmartFake implements _i4.Dio {
  _FakeDio_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResponse_3<T> extends _i1.SmartFake implements _i4.Response<T> {
  _FakeResponse_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AppHttpClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppHttpClient extends _i1.Mock implements _i5.AppHttpClient {
  MockAppHttpClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AppLogger get logger =>
      (super.noSuchMethod(
            Invocation.getter(#logger),
            returnValue: _FakeAppLogger_0(this, Invocation.getter(#logger)),
          )
          as _i2.AppLogger);

  @override
  _i3.Env get env =>
      (super.noSuchMethod(
            Invocation.getter(#env),
            returnValue: _FakeEnv_1(this, Invocation.getter(#env)),
          )
          as _i3.Env);

  @override
  _i4.Dio get dio =>
      (super.noSuchMethod(
            Invocation.getter(#dio),
            returnValue: _FakeDio_2(this, Invocation.getter(#dio)),
          )
          as _i4.Dio);

  @override
  _i6.Future<_i4.Response<dynamic>> request(
    String? path, {
    String? method = 'POST',
    Map<String, dynamic>? queryParameters,
    Object? data,
    Map<String, dynamic>? headers,
    _i4.CancelToken? cancelToken,
    Duration? timeout,
    Map<String, dynamic>? extra,
    _i4.Options? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #request,
              [path],
              {
                #method: method,
                #queryParameters: queryParameters,
                #data: data,
                #headers: headers,
                #cancelToken: cancelToken,
                #timeout: timeout,
                #extra: extra,
                #options: options,
              },
            ),
            returnValue: _i6.Future<_i4.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(
                  #request,
                  [path],
                  {
                    #method: method,
                    #queryParameters: queryParameters,
                    #data: data,
                    #headers: headers,
                    #cancelToken: cancelToken,
                    #timeout: timeout,
                    #extra: extra,
                    #options: options,
                  },
                ),
              ),
            ),
          )
          as _i6.Future<_i4.Response<dynamic>>);

  @override
  _i6.Future<_i4.Response<dynamic>> get(
    String? path, {
    Map<String, dynamic>? queryParameters,
    _i4.Options? options,
    _i4.CancelToken? cancelToken,
    Duration? timeout,
    Map<String, dynamic>? extra,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #get,
              [path],
              {
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #timeout: timeout,
                #extra: extra,
              },
            ),
            returnValue: _i6.Future<_i4.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(
                  #get,
                  [path],
                  {
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #timeout: timeout,
                    #extra: extra,
                  },
                ),
              ),
            ),
          )
          as _i6.Future<_i4.Response<dynamic>>);

  @override
  _i6.Future<_i4.Response<dynamic>> post(
    String? path, {
    Object? data,
    _i4.Options? options,
    _i4.CancelToken? cancelToken,
    Duration? timeout,
    Map<String, dynamic>? extra,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #post,
              [path],
              {
                #data: data,
                #options: options,
                #cancelToken: cancelToken,
                #timeout: timeout,
                #extra: extra,
              },
            ),
            returnValue: _i6.Future<_i4.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(
                  #post,
                  [path],
                  {
                    #data: data,
                    #options: options,
                    #cancelToken: cancelToken,
                    #timeout: timeout,
                    #extra: extra,
                  },
                ),
              ),
            ),
          )
          as _i6.Future<_i4.Response<dynamic>>);

  @override
  _i6.Future<_i4.Response<dynamic>> put(
    String? path, {
    Object? data,
    _i4.Options? options,
    _i4.CancelToken? cancelToken,
    Duration? timeout,
    Map<String, dynamic>? extra,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #put,
              [path],
              {
                #data: data,
                #options: options,
                #cancelToken: cancelToken,
                #timeout: timeout,
                #extra: extra,
              },
            ),
            returnValue: _i6.Future<_i4.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(
                  #put,
                  [path],
                  {
                    #data: data,
                    #options: options,
                    #cancelToken: cancelToken,
                    #timeout: timeout,
                    #extra: extra,
                  },
                ),
              ),
            ),
          )
          as _i6.Future<_i4.Response<dynamic>>);

  @override
  _i6.Future<_i4.Response<dynamic>> delete(
    String? path, {
    Map<String, dynamic>? queryParameters,
    _i4.Options? options,
    _i4.CancelToken? cancelToken,
    Duration? timeout,
    Map<String, dynamic>? extra,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #delete,
              [path],
              {
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #timeout: timeout,
                #extra: extra,
              },
            ),
            returnValue: _i6.Future<_i4.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(
                  #delete,
                  [path],
                  {
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #timeout: timeout,
                    #extra: extra,
                  },
                ),
              ),
            ),
          )
          as _i6.Future<_i4.Response<dynamic>>);
}

/// A class which mocks [AppLogger].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppLogger extends _i1.Mock implements _i2.AppLogger {
  MockAppLogger() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void v(String? message, {Object? e, StackTrace? st, String? tag}) =>
      super.noSuchMethod(
        Invocation.method(#v, [message], {#e: e, #st: st, #tag: tag}),
        returnValueForMissingStub: null,
      );

  @override
  void d(String? message, {Object? e, StackTrace? st, String? tag}) =>
      super.noSuchMethod(
        Invocation.method(#d, [message], {#e: e, #st: st, #tag: tag}),
        returnValueForMissingStub: null,
      );

  @override
  void i(String? message, {Object? e, StackTrace? st, String? tag}) =>
      super.noSuchMethod(
        Invocation.method(#i, [message], {#e: e, #st: st, #tag: tag}),
        returnValueForMissingStub: null,
      );

  @override
  void w(String? message, {Object? e, StackTrace? st, String? tag}) =>
      super.noSuchMethod(
        Invocation.method(#w, [message], {#e: e, #st: st, #tag: tag}),
        returnValueForMissingStub: null,
      );

  @override
  void e(String? message, {Object? e, StackTrace? st, String? tag}) =>
      super.noSuchMethod(
        Invocation.method(#e, [message], {#e: e, #st: st, #tag: tag}),
        returnValueForMissingStub: null,
      );

  @override
  void f(String? message, {Object? e, StackTrace? st, String? tag}) =>
      super.noSuchMethod(
        Invocation.method(#f, [message], {#e: e, #st: st, #tag: tag}),
        returnValueForMissingStub: null,
      );

  @override
  void network(
    String? method,
    String? url, {
    int? statusCode,
    Duration? duration,
    Map<String, dynamic>? requestHeaders,
    Map<String, dynamic>? responseHeaders,
    dynamic requestBody,
    dynamic responseBody,
  }) => super.noSuchMethod(
    Invocation.method(
      #network,
      [method, url],
      {
        #statusCode: statusCode,
        #duration: duration,
        #requestHeaders: requestHeaders,
        #responseHeaders: responseHeaders,
        #requestBody: requestBody,
        #responseBody: responseBody,
      },
    ),
    returnValueForMissingStub: null,
  );

  @override
  void json(
    String? message, {
    dynamic data,
    String? tag,
    _i2.LogLevel? level = _i2.LogLevel.debug,
  }) => super.noSuchMethod(
    Invocation.method(
      #json,
      [message],
      {#data: data, #tag: tag, #level: level},
    ),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [Env].
///
/// See the documentation for Mockito's code generation for more information.
class MockEnv extends _i1.Mock implements _i3.Env {
  MockEnv() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get baseUrl =>
      (super.noSuchMethod(
            Invocation.getter(#baseUrl),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#baseUrl),
            ),
          )
          as String);

  @override
  bool get enableLogging =>
      (super.noSuchMethod(Invocation.getter(#enableLogging), returnValue: false)
          as bool);

  @override
  bool get isTest =>
      (super.noSuchMethod(Invocation.getter(#isTest), returnValue: false)
          as bool);

  @override
  bool get refreshTokenEnabled =>
      (super.noSuchMethod(
            Invocation.getter(#refreshTokenEnabled),
            returnValue: false,
          )
          as bool);
}
