// Mocks generated by Mockito 5.4.6 from annotations
// in testable/test/features/auth/data/repositories/auth_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:testable/core/services/storage_adapter.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [StorageAdapter].
///
/// See the documentation for Mockito's code generation for more information.
class MockStorageAdapter extends _i1.Mock implements _i2.StorageAdapter {
  MockStorageAdapter() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> save(String? key, dynamic value, {bool? secure = false}) =>
      (super.noSuchMethod(
            Invocation.method(#save, [key, value], {#secure: secure}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String?> getString(String? key, {bool? secure = false}) =>
      (super.noSuchMethod(
            Invocation.method(#getString, [key], {#secure: secure}),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<int?> getInt(String? key, {bool? secure = false}) =>
      (super.noSuchMethod(
            Invocation.method(#getInt, [key], {#secure: secure}),
            returnValue: _i3.Future<int?>.value(),
          )
          as _i3.Future<int?>);

  @override
  _i3.Future<bool?> getBool(String? key, {bool? secure = false}) =>
      (super.noSuchMethod(
            Invocation.method(#getBool, [key], {#secure: secure}),
            returnValue: _i3.Future<bool?>.value(),
          )
          as _i3.Future<bool?>);

  @override
  _i3.Future<double?> getDouble(String? key, {bool? secure = false}) =>
      (super.noSuchMethod(
            Invocation.method(#getDouble, [key], {#secure: secure}),
            returnValue: _i3.Future<double?>.value(),
          )
          as _i3.Future<double?>);

  @override
  _i3.Future<List<String>?> getStringList(
    String? key, {
    bool? secure = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getStringList, [key], {#secure: secure}),
            returnValue: _i3.Future<List<String>?>.value(),
          )
          as _i3.Future<List<String>?>);

  @override
  _i3.Future<Map<String, dynamic>?> getMap(
    String? key, {
    bool? secure = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getMap, [key], {#secure: secure}),
            returnValue: _i3.Future<Map<String, dynamic>?>.value(),
          )
          as _i3.Future<Map<String, dynamic>?>);

  @override
  _i3.Future<void> delete(String? key, {bool? secure = false}) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [key], {#secure: secure}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> clear() =>
      (super.noSuchMethod(
            Invocation.method(#clear, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
