// Mocks generated by Mockito 5.4.6 from annotations
// in testable/test/app/router/route_guard_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;
import 'dart:ui' as _i9;

import 'package:auto_route/auto_route.dart' as _i2;
import 'package:auto_route/src/matcher/route_matcher.dart' as _i5;
import 'package:auto_route/src/router/controller/navigation_history/navigation_history_base.dart'
    as _i6;
import 'package:flutter/foundation.dart' as _i4;
import 'package:flutter/material.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeRouteMatch_0<T> extends _i1.SmartFake implements _i2.RouteMatch<T> {
  _FakeRouteMatch_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBuildContext_1 extends _i1.SmartFake implements _i3.BuildContext {
  _FakeBuildContext_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResolverResult_2 extends _i1.SmartFake
    implements _i2.ResolverResult {
  _FakeResolverResult_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeKey_3 extends _i1.SmartFake implements _i4.Key {
  _FakeKey_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePendingRoutesHandler_4 extends _i1.SmartFake
    implements _i2.PendingRoutesHandler {
  _FakePendingRoutesHandler_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePagelessRoutesObserver_5 extends _i1.SmartFake
    implements _i2.PagelessRoutesObserver {
  _FakePagelessRoutesObserver_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeActiveGuardObserver_6 extends _i1.SmartFake
    implements _i2.ActiveGuardObserver {
  _FakeActiveGuardObserver_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGlobalKey_7<T extends _i3.State<_i3.StatefulWidget>>
    extends _i1.SmartFake
    implements _i3.GlobalKey<T> {
  _FakeGlobalKey_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRouteCollection_8 extends _i1.SmartFake
    implements _i2.RouteCollection {
  _FakeRouteCollection_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRouteMatcher_9 extends _i1.SmartFake implements _i5.RouteMatcher {
  _FakeRouteMatcher_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRouteData_10<R> extends _i1.SmartFake implements _i2.RouteData<R> {
  _FakeRouteData_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGlobalObjectKey_11<T extends _i3.State<_i3.StatefulWidget>>
    extends _i1.SmartFake
    implements _i3.GlobalObjectKey<T> {
  _FakeGlobalObjectKey_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNavigationHistory_12 extends _i1.SmartFake
    implements _i6.NavigationHistory {
  _FakeNavigationHistory_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUrlState_13 extends _i1.SmartFake implements _i2.UrlState {
  _FakeUrlState_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRootStackRouter_14 extends _i1.SmartFake
    implements _i2.RootStackRouter {
  _FakeRootStackRouter_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRoutingController_15 extends _i1.SmartFake
    implements _i2.RoutingController {
  _FakeRoutingController_15(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [NavigationResolver].
///
/// See the documentation for Mockito's code generation for more information.
class MockNavigationResolver extends _i1.Mock
    implements _i2.NavigationResolver {
  MockNavigationResolver() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isReevaluating =>
      (super.noSuchMethod(
            Invocation.getter(#isReevaluating),
            returnValue: false,
          )
          as bool);

  @override
  _i2.RouteMatch<dynamic> get route =>
      (super.noSuchMethod(
            Invocation.getter(#route),
            returnValue: _FakeRouteMatch_0<dynamic>(
              this,
              Invocation.getter(#route),
            ),
          )
          as _i2.RouteMatch<dynamic>);

  @override
  String get routeName =>
      (super.noSuchMethod(
            Invocation.getter(#routeName),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#routeName),
            ),
          )
          as String);

  @override
  List<_i2.RouteMatch<dynamic>> get pendingRoutes =>
      (super.noSuchMethod(
            Invocation.getter(#pendingRoutes),
            returnValue: <_i2.RouteMatch<dynamic>>[],
          )
          as List<_i2.RouteMatch<dynamic>>);

  @override
  _i3.BuildContext get context =>
      (super.noSuchMethod(
            Invocation.getter(#context),
            returnValue: _FakeBuildContext_1(this, Invocation.getter(#context)),
          )
          as _i3.BuildContext);

  @override
  bool get isResolved =>
      (super.noSuchMethod(Invocation.getter(#isResolved), returnValue: false)
          as bool);

  @override
  _i8.Future<_i2.ResolverResult> get future =>
      (super.noSuchMethod(
            Invocation.getter(#future),
            returnValue: _i8.Future<_i2.ResolverResult>.value(
              _FakeResolverResult_2(this, Invocation.getter(#future)),
            ),
          )
          as _i8.Future<_i2.ResolverResult>);

  @override
  void next([bool? continueNavigation = true]) => super.noSuchMethod(
    Invocation.method(#next, [continueNavigation]),
    returnValueForMissingStub: null,
  );

  @override
  void resolveNext(bool? continueNavigation, {bool? reevaluateNext = true}) =>
      super.noSuchMethod(
        Invocation.method(
          #resolveNext,
          [continueNavigation],
          {#reevaluateNext: reevaluateNext},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void overrideNext({
    List<_i2.PageRouteInfo<Object?>>? children,
    Object? args,
    Map<String, dynamic>? queryParams,
    String? fragment,
    bool? reevaluateNext = true,
  }) => super.noSuchMethod(
    Invocation.method(#overrideNext, [], {
      #children: children,
      #args: args,
      #queryParams: queryParams,
      #fragment: fragment,
      #reevaluateNext: reevaluateNext,
    }),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<T?> redirectUntil<T extends Object?>(
    _i2.PageRouteInfo<Object?>? route, {
    _i2.OnNavigationFailure? onFailure,
    bool? replace = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #redirectUntil,
              [route],
              {#onFailure: onFailure, #replace: replace},
            ),
            returnValue: _i8.Future<T?>.value(),
          )
          as _i8.Future<T?>);

  @override
  _i8.Future<T?> redirect<T extends Object?>(
    _i2.PageRouteInfo<Object?>? route, {
    _i2.OnNavigationFailure? onFailure,
    bool? replace = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #redirect,
              [route],
              {#onFailure: onFailure, #replace: replace},
            ),
            returnValue: _i8.Future<T?>.value(),
          )
          as _i8.Future<T?>);

  @override
  void nextOrBack([bool? continueNavigation = true]) => super.noSuchMethod(
    Invocation.method(#nextOrBack, [continueNavigation]),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<_i2.ResolverResult> checkGuard(
    _i2.AutoRouteGuard? guard,
    _i2.StackRouter? router,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#checkGuard, [guard, router]),
            returnValue: _i8.Future<_i2.ResolverResult>.value(
              _FakeResolverResult_2(
                this,
                Invocation.method(#checkGuard, [guard, router]),
              ),
            ),
          )
          as _i8.Future<_i2.ResolverResult>);
}

/// A class which mocks [StackRouter].
///
/// See the documentation for Mockito's code generation for more information.
class MockStackRouter extends _i1.Mock implements _i2.StackRouter {
  MockStackRouter() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Key get key =>
      (super.noSuchMethod(
            Invocation.getter(#key),
            returnValue: _FakeKey_3(this, Invocation.getter(#key)),
          )
          as _i4.Key);

  @override
  _i4.Key get matchId =>
      (super.noSuchMethod(
            Invocation.getter(#matchId),
            returnValue: _FakeKey_3(this, Invocation.getter(#matchId)),
          )
          as _i4.Key);

  @override
  _i2.PendingRoutesHandler get pendingRoutesHandler =>
      (super.noSuchMethod(
            Invocation.getter(#pendingRoutesHandler),
            returnValue: _FakePendingRoutesHandler_4(
              this,
              Invocation.getter(#pendingRoutesHandler),
            ),
          )
          as _i2.PendingRoutesHandler);

  @override
  int get stateHash =>
      (super.noSuchMethod(Invocation.getter(#stateHash), returnValue: 0)
          as int);

  @override
  _i2.PagelessRoutesObserver get pagelessRoutesObserver =>
      (super.noSuchMethod(
            Invocation.getter(#pagelessRoutesObserver),
            returnValue: _FakePagelessRoutesObserver_5(
              this,
              Invocation.getter(#pagelessRoutesObserver),
            ),
          )
          as _i2.PagelessRoutesObserver);

  @override
  _i2.ActiveGuardObserver get activeGuardObserver =>
      (super.noSuchMethod(
            Invocation.getter(#activeGuardObserver),
            returnValue: _FakeActiveGuardObserver_6(
              this,
              Invocation.getter(#activeGuardObserver),
            ),
          )
          as _i2.ActiveGuardObserver);

  @override
  _i3.GlobalKey<_i3.NavigatorState> get navigatorKey =>
      (super.noSuchMethod(
            Invocation.getter(#navigatorKey),
            returnValue: _FakeGlobalKey_7<_i3.NavigatorState>(
              this,
              Invocation.getter(#navigatorKey),
            ),
          )
          as _i3.GlobalKey<_i3.NavigatorState>);

  @override
  _i2.RouteCollection get routeCollection =>
      (super.noSuchMethod(
            Invocation.getter(#routeCollection),
            returnValue: _FakeRouteCollection_8(
              this,
              Invocation.getter(#routeCollection),
            ),
          )
          as _i2.RouteCollection);

  @override
  _i5.RouteMatcher get matcher =>
      (super.noSuchMethod(
            Invocation.getter(#matcher),
            returnValue: _FakeRouteMatcher_9(this, Invocation.getter(#matcher)),
          )
          as _i5.RouteMatcher);

  @override
  _i2.RouteData<dynamic> get current =>
      (super.noSuchMethod(
            Invocation.getter(#current),
            returnValue: _FakeRouteData_10<dynamic>(
              this,
              Invocation.getter(#current),
            ),
          )
          as _i2.RouteData<dynamic>);

  @override
  _i2.RouteData<dynamic> get topRoute =>
      (super.noSuchMethod(
            Invocation.getter(#topRoute),
            returnValue: _FakeRouteData_10<dynamic>(
              this,
              Invocation.getter(#topRoute),
            ),
          )
          as _i2.RouteData<dynamic>);

  @override
  bool get hasPagelessTopRoute =>
      (super.noSuchMethod(
            Invocation.getter(#hasPagelessTopRoute),
            returnValue: false,
          )
          as bool);

  @override
  List<_i2.AutoRoutePage<dynamic>> get stack =>
      (super.noSuchMethod(
            Invocation.getter(#stack),
            returnValue: <_i2.AutoRoutePage<dynamic>>[],
          )
          as List<_i2.AutoRoutePage<dynamic>>);

  @override
  bool get ignorePopCompleters =>
      (super.noSuchMethod(
            Invocation.getter(#ignorePopCompleters),
            returnValue: false,
          )
          as bool);

  @override
  _i3.GlobalObjectKey<_i3.State<_i3.StatefulWidget>> get globalRouterKey =>
      (super.noSuchMethod(
            Invocation.getter(#globalRouterKey),
            returnValue: _FakeGlobalObjectKey_11<_i3.State<_i3.StatefulWidget>>(
              this,
              Invocation.getter(#globalRouterKey),
            ),
          )
          as _i3.GlobalObjectKey<_i3.State<_i3.StatefulWidget>>);

  @override
  List<_i2.RoutingController> get childControllers =>
      (super.noSuchMethod(
            Invocation.getter(#childControllers),
            returnValue: <_i2.RoutingController>[],
          )
          as List<_i2.RoutingController>);

  @override
  _i6.NavigationHistory get navigationHistory =>
      (super.noSuchMethod(
            Invocation.getter(#navigationHistory),
            returnValue: _FakeNavigationHistory_12(
              this,
              Invocation.getter(#navigationHistory),
            ),
          )
          as _i6.NavigationHistory);

  @override
  _i2.UrlState get urlState =>
      (super.noSuchMethod(
            Invocation.getter(#urlState),
            returnValue: _FakeUrlState_13(this, Invocation.getter(#urlState)),
          )
          as _i2.UrlState);

  @override
  String get currentPath =>
      (super.noSuchMethod(
            Invocation.getter(#currentPath),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#currentPath),
            ),
          )
          as String);

  @override
  String get currentUrl =>
      (super.noSuchMethod(
            Invocation.getter(#currentUrl),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#currentUrl),
            ),
          )
          as String);

  @override
  List<_i2.RouteData<dynamic>> get stackData =>
      (super.noSuchMethod(
            Invocation.getter(#stackData),
            returnValue: <_i2.RouteData<dynamic>>[],
          )
          as List<_i2.RouteData<dynamic>>);

  @override
  bool get managedByWidget =>
      (super.noSuchMethod(
            Invocation.getter(#managedByWidget),
            returnValue: false,
          )
          as bool);

  @override
  bool get isTopMost =>
      (super.noSuchMethod(Invocation.getter(#isTopMost), returnValue: false)
          as bool);

  @override
  bool get canNavigateBack =>
      (super.noSuchMethod(
            Invocation.getter(#canNavigateBack),
            returnValue: false,
          )
          as bool);

  @override
  _i2.RootStackRouter get root =>
      (super.noSuchMethod(
            Invocation.getter(#root),
            returnValue: _FakeRootStackRouter_14(
              this,
              Invocation.getter(#root),
            ),
          )
          as _i2.RootStackRouter);

  @override
  bool get isRoot =>
      (super.noSuchMethod(Invocation.getter(#isRoot), returnValue: false)
          as bool);

  @override
  _i2.RouteMatch<dynamic> get topMatch =>
      (super.noSuchMethod(
            Invocation.getter(#topMatch),
            returnValue: _FakeRouteMatch_0<dynamic>(
              this,
              Invocation.getter(#topMatch),
            ),
          )
          as _i2.RouteMatch<dynamic>);

  @override
  _i2.RouteData<dynamic> get routeData =>
      (super.noSuchMethod(
            Invocation.getter(#routeData),
            returnValue: _FakeRouteData_10<dynamic>(
              this,
              Invocation.getter(#routeData),
            ),
          )
          as _i2.RouteData<dynamic>);

  @override
  bool get hasEntries =>
      (super.noSuchMethod(Invocation.getter(#hasEntries), returnValue: false)
          as bool);

  @override
  int get pageCount =>
      (super.noSuchMethod(Invocation.getter(#pageCount), returnValue: 0)
          as int);

  @override
  List<_i2.RouteMatch<dynamic>> get currentSegments =>
      (super.noSuchMethod(
            Invocation.getter(#currentSegments),
            returnValue: <_i2.RouteMatch<dynamic>>[],
          )
          as List<_i2.RouteMatch<dynamic>>);

  @override
  set ignorePopCompleters(bool? value) => super.noSuchMethod(
    Invocation.setter(#ignorePopCompleters, value),
    returnValueForMissingStub: null,
  );

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<void> reevaluateGuards() =>
      (super.noSuchMethod(
            Invocation.method(#reevaluateGuards, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  bool canPop({
    bool? ignoreChildRoutes = false,
    bool? ignoreParentRoutes = false,
    bool? ignorePagelessRoutes = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#canPop, [], {
              #ignoreChildRoutes: ignoreChildRoutes,
              #ignoreParentRoutes: ignoreParentRoutes,
              #ignorePagelessRoutes: ignorePagelessRoutes,
            }),
            returnValue: false,
          )
          as bool);

  @override
  _i8.Future<T?> pushWidget<T extends Object?>(
    _i3.Widget? widget, {
    _i3.RouteTransitionsBuilder? transitionBuilder,
    bool? fullscreenDialog = false,
    Duration? transitionDuration = const Duration(milliseconds: 300),
    bool? opaque = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #pushWidget,
              [widget],
              {
                #transitionBuilder: transitionBuilder,
                #fullscreenDialog: fullscreenDialog,
                #transitionDuration: transitionDuration,
                #opaque: opaque,
              },
            ),
            returnValue: _i8.Future<T?>.value(),
          )
          as _i8.Future<T?>);

  @override
  _i8.Future<T?> pushNativeRoute<T extends Object?>(_i3.Route<T>? route) =>
      (super.noSuchMethod(
            Invocation.method(#pushNativeRoute, [route]),
            returnValue: _i8.Future<T?>.value(),
          )
          as _i8.Future<T?>);

  @override
  _i8.Future<bool> maybePop<T extends Object?>([T? result]) =>
      (super.noSuchMethod(
            Invocation.method(#maybePop, [result]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  void pop<T extends Object?>([T? result]) => super.noSuchMethod(
    Invocation.method(#pop, [result]),
    returnValueForMissingStub: null,
  );

  @override
  void popForced<T extends Object?>([T? result]) => super.noSuchMethod(
    Invocation.method(#popForced, [result]),
    returnValueForMissingStub: null,
  );

  @override
  bool removeLast() =>
      (super.noSuchMethod(
            Invocation.method(#removeLast, []),
            returnValue: false,
          )
          as bool);

  @override
  void removeRoute(_i2.RouteData<dynamic>? route, {bool? notify = true}) =>
      super.noSuchMethod(
        Invocation.method(#removeRoute, [route], {#notify: notify}),
        returnValueForMissingStub: null,
      );

  @override
  void onPopPage(_i2.AutoRoutePage<Object?>? page) => super.noSuchMethod(
    Invocation.method(#onPopPage, [page]),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<T?> push<T extends Object?>(
    _i2.PageRouteInfo<Object?>? route, {
    _i2.OnNavigationFailure? onFailure,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#push, [route], {#onFailure: onFailure}),
            returnValue: _i8.Future<T?>.value(),
          )
          as _i8.Future<T?>);

  @override
  _i8.Future<void> insert(
    _i2.PageRouteInfo<Object?>? route, {
    int? index = 0,
    _i2.OnNavigationFailure? onFailure,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #insert,
              [route],
              {#index: index, #onFailure: onFailure},
            ),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<T?> replace<T extends Object?>(
    _i2.PageRouteInfo<Object?>? route, {
    _i2.OnNavigationFailure? onFailure,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#replace, [route], {#onFailure: onFailure}),
            returnValue: _i8.Future<T?>.value(),
          )
          as _i8.Future<T?>);

  @override
  _i8.Future<void> pushAll(
    List<_i2.PageRouteInfo<Object?>>? routes, {
    _i2.OnNavigationFailure? onFailure,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#pushAll, [routes], {#onFailure: onFailure}),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> popAndPushAll(
    List<_i2.PageRouteInfo<Object?>>? routes, {
    dynamic onFailure,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #popAndPushAll,
              [routes],
              {#onFailure: onFailure},
            ),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> replaceAll(
    List<_i2.PageRouteInfo<Object?>>? routes, {
    _i2.OnNavigationFailure? onFailure,
    bool? updateExistingRoutes = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #replaceAll,
              [routes],
              {
                #onFailure: onFailure,
                #updateExistingRoutes: updateExistingRoutes,
              },
            ),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  void popUntilRoot() => super.noSuchMethod(
    Invocation.method(#popUntilRoot, []),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<T?> popAndPush<T extends Object?, TO extends Object?>(
    _i2.PageRouteInfo<Object?>? route, {
    TO? result,
    _i2.OnNavigationFailure? onFailure,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #popAndPush,
              [route],
              {#result: result, #onFailure: onFailure},
            ),
            returnValue: _i8.Future<T?>.value(),
          )
          as _i8.Future<T?>);

  @override
  bool removeUntil(_i2.RouteDataPredicate? predicate, {bool? scoped = true}) =>
      (super.noSuchMethod(
            Invocation.method(#removeUntil, [predicate], {#scoped: scoped}),
            returnValue: false,
          )
          as bool);

  @override
  void popUntil(_i3.RoutePredicate? predicate, {bool? scoped = true}) =>
      super.noSuchMethod(
        Invocation.method(#popUntil, [predicate], {#scoped: scoped}),
        returnValueForMissingStub: null,
      );

  @override
  bool removeWhere(_i2.RouteDataPredicate? predicate, {bool? notify = true}) =>
      (super.noSuchMethod(
            Invocation.method(#removeWhere, [predicate], {#notify: notify}),
            returnValue: false,
          )
          as bool);

  @override
  void updateDeclarativeRoutes(List<_i2.PageRouteInfo<Object?>>? routes) =>
      super.noSuchMethod(
        Invocation.method(#updateDeclarativeRoutes, [routes]),
        returnValueForMissingStub: null,
      );

  @override
  _i8.Future<void> navigateAll(
    List<_i2.RouteMatch<dynamic>>? routes, {
    _i2.OnNavigationFailure? onFailure,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#navigateAll, [routes], {#onFailure: onFailure}),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<T?> pushAndPopUntil<T extends Object?>(
    _i2.PageRouteInfo<Object?>? route, {
    required _i3.RoutePredicate? predicate,
    bool? scopedPopUntil = true,
    _i2.OnNavigationFailure? onFailure,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #pushAndPopUntil,
              [route],
              {
                #predicate: predicate,
                #scopedPopUntil: scopedPopUntil,
                #onFailure: onFailure,
              },
            ),
            returnValue: _i8.Future<T?>.value(),
          )
          as _i8.Future<T?>);

  @override
  _i8.Future<T?> replacePath<T extends Object?>(
    String? path, {
    bool? includePrefixMatches = false,
    _i2.OnNavigationFailure? onFailure,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #replacePath,
              [path],
              {
                #includePrefixMatches: includePrefixMatches,
                #onFailure: onFailure,
              },
            ),
            returnValue: _i8.Future<T?>.value(),
          )
          as _i8.Future<T?>);

  @override
  _i8.Future<T?> replaceNamed<T extends Object?>(
    String? path, {
    bool? includePrefixMatches = false,
    _i2.OnNavigationFailure? onFailure,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #replaceNamed,
              [path],
              {
                #includePrefixMatches: includePrefixMatches,
                #onFailure: onFailure,
              },
            ),
            returnValue: _i8.Future<T?>.value(),
          )
          as _i8.Future<T?>);

  @override
  _i8.Future<T?> pushPath<T extends Object?>(
    String? path, {
    bool? includePrefixMatches = false,
    _i2.OnNavigationFailure? onFailure,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #pushPath,
              [path],
              {
                #includePrefixMatches: includePrefixMatches,
                #onFailure: onFailure,
              },
            ),
            returnValue: _i8.Future<T?>.value(),
          )
          as _i8.Future<T?>);

  @override
  _i8.Future<T?> pushNamed<T extends Object?>(
    String? path, {
    bool? includePrefixMatches = false,
    _i2.OnNavigationFailure? onFailure,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #pushNamed,
              [path],
              {
                #includePrefixMatches: includePrefixMatches,
                #onFailure: onFailure,
              },
            ),
            returnValue: _i8.Future<T?>.value(),
          )
          as _i8.Future<T?>);

  @override
  void popUntilRouteWithName(String? name, {bool? scoped = true}) =>
      super.noSuchMethod(
        Invocation.method(#popUntilRouteWithName, [name], {#scoped: scoped}),
        returnValueForMissingStub: null,
      );

  @override
  void popUntilRouteWithPath(String? path, {bool? scoped = true}) =>
      super.noSuchMethod(
        Invocation.method(#popUntilRouteWithPath, [path], {#scoped: scoped}),
        returnValueForMissingStub: null,
      );

  @override
  void markUrlStateForReplace() => super.noSuchMethod(
    Invocation.method(#markUrlStateForReplace, []),
    returnValueForMissingStub: null,
  );

  @override
  void attachChildController(_i2.RoutingController? childController) =>
      super.noSuchMethod(
        Invocation.method(#attachChildController, [childController]),
        returnValueForMissingStub: null,
      );

  @override
  void removeChildController(_i2.RoutingController? childController) =>
      super.noSuchMethod(
        Invocation.method(#removeChildController, [childController]),
        returnValueForMissingStub: null,
      );

  @override
  void notifyAll({bool? forceUrlRebuild = false}) => super.noSuchMethod(
    Invocation.method(#notifyAll, [], {#forceUrlRebuild: forceUrlRebuild}),
    returnValueForMissingStub: null,
  );

  @override
  List<_i2.HierarchySegment> currentHierarchy({
    bool? asPath = false,
    bool? ignorePending = false,
    bool? ignoreParams = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#currentHierarchy, [], {
              #asPath: asPath,
              #ignorePending: ignorePending,
              #ignoreParams: ignoreParams,
            }),
            returnValue: <_i2.HierarchySegment>[],
          )
          as List<_i2.HierarchySegment>);

  @override
  bool isRouteActive(String? routeName) =>
      (super.noSuchMethod(
            Invocation.method(#isRouteActive, [routeName]),
            returnValue: false,
          )
          as bool);

  @override
  bool isRouteDataActive(_i2.RouteData<dynamic>? data) =>
      (super.noSuchMethod(
            Invocation.method(#isRouteDataActive, [data]),
            returnValue: false,
          )
          as bool);

  @override
  bool isPathActive(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#isPathActive, [path]),
            returnValue: false,
          )
          as bool);

  @override
  _i2.RouteMatch<dynamic>? match(_i2.PageRouteInfo<Object?>? route) =>
      (super.noSuchMethod(Invocation.method(#match, [route]))
          as _i2.RouteMatch<dynamic>?);

  @override
  _i8.Future<dynamic> navigate(
    _i2.PageRouteInfo<Object?>? route, {
    _i2.OnNavigationFailure? onFailure,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#navigate, [route], {#onFailure: onFailure}),
            returnValue: _i8.Future<dynamic>.value(),
          )
          as _i8.Future<dynamic>);

  @override
  _i8.Future<void> navigatePath(
    String? path, {
    bool? includePrefixMatches = false,
    _i2.OnNavigationFailure? onFailure,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #navigatePath,
              [path],
              {
                #includePrefixMatches: includePrefixMatches,
                #onFailure: onFailure,
              },
            ),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> navigateNamed(
    String? path, {
    bool? includePrefixMatches = false,
    _i2.OnNavigationFailure? onFailure,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #navigateNamed,
              [path],
              {
                #includePrefixMatches: includePrefixMatches,
                #onFailure: onFailure,
              },
            ),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  void back() => super.noSuchMethod(
    Invocation.method(#back, []),
    returnValueForMissingStub: null,
  );

  @override
  void pushPathState(Object? state) => super.noSuchMethod(
    Invocation.method(#pushPathState, [state]),
    returnValueForMissingStub: null,
  );

  @override
  _i2.RoutingController topMostRouter({bool? ignorePagelessRoutes = false}) =>
      (super.noSuchMethod(
            Invocation.method(#topMostRouter, [], {
              #ignorePagelessRoutes: ignorePagelessRoutes,
            }),
            returnValue: _FakeRoutingController_15(
              this,
              Invocation.method(#topMostRouter, [], {
                #ignorePagelessRoutes: ignorePagelessRoutes,
              }),
            ),
          )
          as _i2.RoutingController);

  @override
  void updateRouteData(_i2.RouteData<dynamic>? data) => super.noSuchMethod(
    Invocation.method(#updateRouteData, [data]),
    returnValueForMissingStub: null,
  );

  @override
  T? innerRouterOf<T extends _i2.RoutingController>(String? routeName) =>
      (super.noSuchMethod(Invocation.method(#innerRouterOf, [routeName]))
          as T?);

  @override
  _i8.Future<bool> maybePopTop<T extends Object?>([T? result]) =>
      (super.noSuchMethod(
            Invocation.method(#maybePopTop, [result]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  void popTop<T extends Object?>([T? result]) => super.noSuchMethod(
    Invocation.method(#popTop, [result]),
    returnValueForMissingStub: null,
  );

  @override
  bool childrenCanPop({bool? ignorePagelessRoutes = false}) =>
      (super.noSuchMethod(
            Invocation.method(#childrenCanPop, [], {
              #ignorePagelessRoutes: ignorePagelessRoutes,
            }),
            returnValue: false,
          )
          as bool);

  @override
  bool activeRouterCanPop({bool? ignorePagelessRoutes = false}) =>
      (super.noSuchMethod(
            Invocation.method(#activeRouterCanPop, [], {
              #ignorePagelessRoutes: ignorePagelessRoutes,
            }),
            returnValue: false,
          )
          as bool);

  @override
  _i2.PageRouteInfo<Object?>? buildPageRoute(
    String? path, {
    bool? includePrefixMatches = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #buildPageRoute,
              [path],
              {#includePrefixMatches: includePrefixMatches},
            ),
          )
          as _i2.PageRouteInfo<Object?>?);

  @override
  List<_i2.PageRouteInfo<Object?>>? buildPageRoutesStack(
    String? path, {
    bool? includePrefixMatches = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #buildPageRoutesStack,
              [path],
              {#includePrefixMatches: includePrefixMatches},
            ),
          )
          as List<_i2.PageRouteInfo<Object?>>?);

  @override
  void addListener(_i9.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i9.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
